baseURL = 'https://blog.echo.sh/'
languageCode = 'en-nz'
title = 'jonathan chow'
theme = 'paper'
disableKinds = ["taxonomy", "term"]

[markup]
  [markup.highlight]
    style = 'rose-pine-dawn'

[pagination]
pagerSize = 5 # articles per page

[params]
color = 'light'
github = 'echojc'
linkedin = 'echojc'

# Main menu Items

[[menu.main]]
name = "posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "cv"
url = "/cv"
weight = 2
