baseURL = 'https://blog.echo.sh/'
languageCode = 'en-nz'
title = 'jonathan chow'
theme = 'paper'

# Code Highlight
pygmentsstyle = "solarized-light"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[pagination]
pagerSize = 3 # articles per page

[params]
mode="light" # color-mode â†’ light,dark,toggle or auto
useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
mathjax = false # enable MathJax support
katex = false # enable KaTeX support

# Main menu Items

[[menu.main]]
name = "posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "cv"
url = "/cv"
weight = 2

[[menu.main]]
name = "github"
url = "https://github.com/echojc"
weight = 3
