baseURL = 'https://blog.echo.sh/'
languageCode = 'en-nz'
title = 'jonathan chow'
theme = 'paper'
disableKinds = ["taxonomy", "term"]

[markup]
  [markup.highlight]
    style = 'catppuccin-latte'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[pagination]
pagerSize = 5 # articles per page

[params]
color = 'light'
github = 'echojc'
linkedin = 'echojc'

# Main menu Items

[[menu.main]]
name = "resume"
url = "/cv"
weight = 1
